title: credits.txt
descriptions: credits for website contributors
url: https://creditstxt.com
homepage: https://creditstxt.com
repository: kemitchell/creditstxt.com
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - credits.rb
  - Rakefile
